version: "4.3"

services:
  #MongoDB
  mongo_db:
    container_name: database_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db

  backend_service:
    build: ./backend
    ports:
      - 8000:8000
    environment:
      PORT: 8000
      DB_URL: mongodb://mongo_db:27017/
    depends_on:
      - mongo_db
 
  client_service:
    build: ./client
    ports:
      - 5173:5173
    depends_on:
      - mongo_db
      - backend_service

volumes:
  mongo_db: {}